/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Callme: typeof import('./src/components/callme/index.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Picture: typeof import('./src/components/Picture.vue')['default']
    Praise: typeof import('./src/components/Praise.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WishBtn: typeof import('./src/components/WishBtn.vue')['default']
    WishPanel: typeof import('./src/components/WishPanel.vue')['default']
  }
}
