// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Callme: typeof import('./src/components/callme/index.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Picture: typeof import('./src/components/Picture.vue')['default']
    Praise: typeof import('./src/components/Praise.vue')['default']
    WishBtn: typeof import('./src/components/WishBtn.vue')['default']
  }
}

export { }
