# This is a basic workflow to help you get started with Actions

name: prod-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    types: [ assigned ]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # 配置rsa密钥自动登陆
      - uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup knownhosts
        run: ssh-keyscan ${{ secrets.REMOTE_ORIGIN }} >> ~/.ssh/known_hosts

      - name: Install dependence
        run: |
          echo 开始----安装依赖
          yarn install
      - name: Build
        run: |
          echo 开始----构建
          yarn build
      - name: Compress dist
        run: |
          echo 开始----压缩
          yarn compress
      # 上传压缩的内容
      - name: Upload package
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "ep2.tar.gz"
          REMOTE_HOST: ${{ secrets.REMOTE_ORIGIN }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
      # 部署上传的包
      - name: Deploy
        run: |
          echo 开始----部署
          yarn deploy